document.getElementById("generateVideoBtn").addEventListener("click", async () => {
  const prompt = document.getElementById("videoPrompt").value.trim();
  const videoOutput = document.getElementById("videoOutput");
  if (!prompt) return alert("Please describe the video.");

  videoOutput.innerHTML = "<p>Suleiman AI is generating your video...</p>";

  try {
    const res = await fetch("/api/memories", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt }),
    });
    const data = await res.json();

    if (data.videoUrl) {
      videoOutput.innerHTML = `
        <video controls autoplay>
          <source src="${data.videoUrl}" type="video/mp4">
        </video>
        <p><b>Video generated by Suleiman AI</b></p>
      `;
    } else {
      videoOutput.innerHTML = `<p>${data.error || "Video generation failed."}</p>`;
    }
  } catch {
    videoOutput.innerHTML = "<p>Network error generating video.</p>";
  }
});
